version: 2
jobs:
  build:
    docker:
      - image: archlinux/base:latest
    steps:
      - run:
          name: Update and install dependencies
          command: pacman -Syu --noconfirm --noprogressbar git openssh make shellcheck
      - checkout
      - run:
          name: Check
          command: make check
